### ISSUE TITLE
Not working on Rails 3.2.8?

### ISSUE THREAD

**Issue by andreofthecape** [spilliton/randumb#14]
Hi,

Got gem in gemfile, and shows in bundle but when I use it in controller it returns no records. In console it throws an undefined method 'random' . ie User.all works User.random doesnt. On sqlite database, Rails 3.2.8
